DELETE FROM CUSTOMER;
DELETE FROM PRODUCT;

INSERT INTO PRODUCT (PRODUCT_CODE,COST,STATUS) VALUES ('PRODUCT_001','50','Active');
INSERT INTO PRODUCT (PRODUCT_CODE,COST,STATUS) VALUES ('PRODUCT_002','100','InActive');
INSERT INTO PRODUCT (PRODUCT_CODE,COST,STATUS) VALUES ('PRODUCT_003','200','Active');
INSERT INTO PRODUCT (PRODUCT_CODE,COST,STATUS) VALUES ('PRODUCT_004','10','InActive');
INSERT INTO PRODUCT (PRODUCT_CODE,COST,STATUS) VALUES ('PRODUCT_005','500','Active');


INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME,EMAIL,LOCATION) VALUES ('10001','Tony','Stark','tony.stark@gmail.com','Australia');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME,EMAIL,LOCATION) VALUES ('10002','Bruce','Banner','bruce.banner@gmail.com','US');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME,EMAIL,LOCATION) VALUES ('10003','Steve','Rogers','stever.rogers@gmail.com','Australia');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME,EMAIL,LOCATION) VALUES ('10004','Wanda','Maximoff','wanda.maximoff@gmail.com','US');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME,EMAIL,LOCATION) VALUES ('10005','Natasha','Romanoff','natasha.romanoff@gmail.com','Australia');
